variables:
    PLUGIN_NAME : 'thoth'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_5_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/omp/unit_tests.yml'

.unit_test_template:
  before_script:
    - composer install

static_analysis:
  stage: validation
  image: $CI_IMAGE_OMP
  needs: []
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  variables:
    PHP_VERSION: '8.4'
    THOTH_PKP_ROOT: '/var/www/omp'
  before_script:
    - update-alternatives --set php /usr/bin/php$PHP_VERSION
    - composer install
  script:
    - cd "$CI_PROJECT_DIR"
    - vendor/bin/phpstan analyse --no-progress --memory-limit=512M
